name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v5.0.0
        with:
          node-version: '22.11.0'
      - run: npm install
      - run: npm run decode:b64
      - run: npm test
      - run: npm run build
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: dist
