name: Codex Assets → PR
on:
  workflow_dispatch: {}
  push:
    branches:
      - codex-drafts/**
jobs:
  decode-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Decode base64 assets
        id: decode
        run: |
          set +e
          node scripts/decode-assets.js
          echo "decode_rc=$?" >> $GITHUB_OUTPUT
          exit 0
      - name: Bail if nothing to decode
        if: steps.decode.outputs.decode_rc == '2'
        run: echo "No new .b64 assets; skipping commit/PR."
      - name: Configure git author
        if: steps.decode.outputs.decode_rc == '0'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit decoded assets
        if: steps.decode.outputs.decode_rc == '0'
        id: commit
        run: |
          CHANGES=$(git status --porcelain)
          if [ -z "$CHANGES" ]; then
            echo "No changes after decode."
            exit 0
          fi
          BRANCH="codex/assets-$(date +'%Y%m%d-%H%M%S')"
          git checkout -b "$BRANCH"
          git add -A
          git commit -m "bridge: materialize binary assets from Codex"
          git push --set-upstream origin "$BRANCH"
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT
      - name: Open Pull Request
        if: steps.decode.outputs.decode_rc == '0'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'bridge: materialize binary assets from Codex'
          branch: ${{ steps.commit.outputs.branch_name || '' }}
          title: 'Materialize Codex binary assets'
          body: |
            Auto-decoded `.b64` assets from `assets/_incoming/` into binaries under `assets/`.
            Removed the .b64 placeholders.
          base: main
